/**
 * Affiliate provider registry — static data for enriching backend alternatives
 * with affiliate tracking links, display metadata, and compliance info.
 */

// ── Types ──────────────────────────────────────────────────────────

export type AffiliateNetwork = 'generic' | 'impact' | 'cj' | 'partnerstack' | 'shareasale'

export interface AffiliateProvider {
  providerId: string
  name: string
  categoryTags: string[]
  baseUrl: string
  affiliateUrl: string | null
  network: AffiliateNetwork
  countryAvailability: string[]
  isActive: boolean
  priority: number
  terms: string
  matchNames: string[]
}

interface RegistryConfig {
  disclosureText: string
  footerNote: string
}

// ── Provider Data ──────────────────────────────────────────────────

const PROVIDERS: AffiliateProvider[] = [
  // ── Streaming ──
  {
    providerId: 'tubi',
    name: 'Tubi',
    categoryTags: ['streaming'],
    baseUrl: 'https://tubitv.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US', 'CA'],
    isActive: true,
    priority: 70,
    terms: 'Free with ads',
    matchNames: ['tubi'],
  },
  {
    providerId: 'pluto-tv',
    name: 'Pluto TV',
    categoryTags: ['streaming'],
    baseUrl: 'https://pluto.tv',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US', 'CA', 'GB'],
    isActive: true,
    priority: 65,
    terms: 'Free with ads',
    matchNames: ['pluto tv'],
  },
  {
    providerId: 'amazon-prime-video',
    name: 'Amazon Prime Video',
    categoryTags: ['streaming'],
    baseUrl: 'https://www.amazon.com/Prime-Video/b?node=2676882011',
    affiliateUrl: 'https://www.amazon.com/Prime-Video/b?node=2676882011&tag=leakywallet-20',
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 60,
    terms: 'Included with Prime',
    matchNames: ['amazon prime video'],
  },
  {
    providerId: 'peacock-free',
    name: 'Peacock Free',
    categoryTags: ['streaming'],
    baseUrl: 'https://www.peacocktv.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US'],
    isActive: true,
    priority: 55,
    terms: 'Free tier with ads',
    matchNames: ['peacock free'],
  },
  {
    providerId: 'paramount-essential',
    name: 'Paramount+ Essential',
    categoryTags: ['streaming'],
    baseUrl: 'https://www.paramountplus.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US', 'CA'],
    isActive: true,
    priority: 50,
    terms: '$5.99/mo with ads',
    matchNames: ['paramount+ essential', 'paramount essential'],
  },
  {
    providerId: 'disney-plus-ads',
    name: 'Disney+ with Ads',
    categoryTags: ['streaming'],
    baseUrl: 'https://www.disneyplus.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US'],
    isActive: true,
    priority: 50,
    terms: '$7.99/mo with ads',
    matchNames: ['disney+ with ads'],
  },
  {
    providerId: 'bundle-hulu',
    name: 'Bundle with Hulu',
    categoryTags: ['streaming'],
    baseUrl: 'https://www.disneyplus.com/welcome/disney-hulu-espn-bundle',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US'],
    isActive: true,
    priority: 40,
    terms: '$9.99/mo bundle',
    matchNames: ['bundle with hulu'],
  },
  {
    providerId: 'max-with-ads',
    name: 'Max with Ads',
    categoryTags: ['streaming'],
    baseUrl: 'https://www.max.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US'],
    isActive: true,
    priority: 45,
    terms: '$9.99/mo with ads',
    matchNames: ['max with ads'],
  },
  {
    providerId: 'rotate-monthly',
    name: 'Rotate monthly',
    categoryTags: ['streaming'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 30,
    terms: 'Subscribe, binge, cancel',
    matchNames: ['rotate monthly'],
  },
  {
    providerId: 'youtube-music',
    name: 'YouTube Music',
    categoryTags: ['streaming'],
    baseUrl: 'https://music.youtube.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 50,
    terms: '$10.99/mo',
    matchNames: ['youtube music'],
  },
  {
    providerId: 'amazon-music',
    name: 'Amazon Music',
    categoryTags: ['streaming'],
    baseUrl: 'https://music.amazon.com',
    affiliateUrl: 'https://www.amazon.com/music/unlimited?tag=leakywallet-20',
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 55,
    terms: 'Free with Prime',
    matchNames: ['amazon music'],
  },
  {
    providerId: 'spotify-free',
    name: 'Spotify Free',
    categoryTags: ['streaming'],
    baseUrl: 'https://www.spotify.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 60,
    terms: 'Free with ads',
    matchNames: ['spotify free'],
  },
  {
    providerId: 'ublock-origin',
    name: 'uBlock Origin',
    categoryTags: ['software', 'streaming'],
    baseUrl: 'https://ublockorigin.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 40,
    terms: 'Free browser extension',
    matchNames: ['ublock origin'],
  },
  {
    providerId: 'youtube-music-only',
    name: 'YouTube Music only',
    categoryTags: ['streaming'],
    baseUrl: 'https://music.youtube.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 45,
    terms: '$10.99/mo',
    matchNames: ['youtube music only'],
  },

  // ── Food Delivery ──
  {
    providerId: 'restaurant-pickup',
    name: 'Restaurant pickup',
    categoryTags: ['food_delivery'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 70,
    terms: 'Save on fees',
    matchNames: ['restaurant pickup'],
  },
  {
    providerId: 'doordash-dashpass',
    name: 'DoorDash DashPass',
    categoryTags: ['food_delivery'],
    baseUrl: 'https://www.doordash.com/dashpass',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US', 'CA'],
    isActive: true,
    priority: 50,
    terms: '$9.99/mo',
    matchNames: ['doordash dashpass'],
  },
  {
    providerId: 'meal-prep',
    name: 'Meal prep Sunday',
    categoryTags: ['food_delivery'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 60,
    terms: 'Batch cook',
    matchNames: ['meal prep sunday'],
  },
  {
    providerId: 'direct-restaurant',
    name: 'Direct restaurant ordering',
    categoryTags: ['food_delivery'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 65,
    terms: 'Order direct',
    matchNames: ['direct restaurant ordering'],
  },
  {
    providerId: 'local-pickup',
    name: 'Local pickup',
    categoryTags: ['food_delivery'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 55,
    terms: 'Skip the fees',
    matchNames: ['local pickup'],
  },
  {
    providerId: 'restaurant-direct',
    name: 'Restaurant direct',
    categoryTags: ['food_delivery'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 55,
    terms: 'Call restaurant',
    matchNames: ['restaurant direct'],
  },
  {
    providerId: 'hey-you',
    name: 'Hey You',
    categoryTags: ['food_delivery'],
    baseUrl: 'https://www.heyyou.com.au',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['AU'],
    isActive: true,
    priority: 40,
    terms: 'Order ahead, earn rewards',
    matchNames: ['hey you'],
  },
  {
    providerId: 'grubhub-plus',
    name: 'Grubhub+',
    categoryTags: ['food_delivery'],
    baseUrl: 'https://www.grubhub.com/plus',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US'],
    isActive: true,
    priority: 45,
    terms: '$9.99/mo free delivery',
    matchNames: ['grubhub+'],
  },
  {
    providerId: 'uber-eats',
    name: 'Uber Eats',
    categoryTags: ['food_delivery'],
    baseUrl: 'https://www.ubereats.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 40,
    terms: 'Same company as Postmates',
    matchNames: ['uber eats'],
  },

  // ── Rideshare ──
  {
    providerId: 'public-transit',
    name: 'Public transit',
    categoryTags: ['rideshare'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 70,
    terms: 'Often 80% cheaper',
    matchNames: ['public transit'],
  },
  {
    providerId: 'lyft',
    name: 'Lyft',
    categoryTags: ['rideshare'],
    baseUrl: 'https://www.lyft.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US', 'CA'],
    isActive: true,
    priority: 50,
    terms: 'Compare prices',
    matchNames: ['lyft'],
  },
  {
    providerId: 'uber-pool',
    name: 'Uber Pool/Share',
    categoryTags: ['rideshare'],
    baseUrl: 'https://www.uber.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US'],
    isActive: true,
    priority: 55,
    terms: 'Save 30-50%',
    matchNames: ['uber pool/share', 'uber pool'],
  },
  {
    providerId: 'uber',
    name: 'Uber',
    categoryTags: ['rideshare'],
    baseUrl: 'https://www.uber.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 45,
    terms: 'Compare prices',
    matchNames: ['uber'],
  },
  {
    providerId: 'bike-share',
    name: 'Bike share',
    categoryTags: ['rideshare'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 50,
    terms: 'Often free first 30 mins',
    matchNames: ['bike share'],
  },

  // ── Fitness ──
  {
    providerId: 'youtube-workouts',
    name: 'YouTube workouts',
    categoryTags: ['fitness'],
    baseUrl: 'https://www.youtube.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 65,
    terms: 'Free',
    matchNames: ['youtube workouts'],
  },
  {
    providerId: 'outdoor-running',
    name: 'Outdoor running',
    categoryTags: ['fitness'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 60,
    terms: 'Free cardio',
    matchNames: ['outdoor running'],
  },
  {
    providerId: 'planet-fitness',
    name: 'Planet Fitness',
    categoryTags: ['fitness'],
    baseUrl: 'https://www.planetfitness.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US', 'CA'],
    isActive: true,
    priority: 55,
    terms: '$10/mo',
    matchNames: ['planet fitness'],
  },
  {
    providerId: 'classpass',
    name: 'ClassPass',
    categoryTags: ['fitness'],
    baseUrl: 'https://classpass.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US'],
    isActive: true,
    priority: 45,
    terms: 'From $49/mo',
    matchNames: ['classpass'],
  },
  {
    providerId: 'peloton-app',
    name: 'Peloton app only',
    categoryTags: ['fitness'],
    baseUrl: 'https://www.onepeloton.com/app',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US', 'CA', 'GB'],
    isActive: true,
    priority: 50,
    terms: '$12.99/mo',
    matchNames: ['peloton app only'],
  },
  {
    providerId: 'apple-fitness-plus',
    name: 'Apple Fitness+',
    categoryTags: ['fitness'],
    baseUrl: 'https://www.apple.com/apple-fitness-plus',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 50,
    terms: '$9.99/mo',
    matchNames: ['apple fitness+', 'apple fitness plus'],
  },
  {
    providerId: 'youtube-fitness',
    name: 'YouTube fitness',
    categoryTags: ['fitness'],
    baseUrl: 'https://www.youtube.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 60,
    terms: 'Free',
    matchNames: ['youtube fitness'],
  },
  {
    providerId: 'one-gym',
    name: 'One gym membership',
    categoryTags: ['fitness'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 40,
    terms: '~$30/mo',
    matchNames: ['one gym membership'],
  },
  {
    providerId: 'free-trial-hopping',
    name: 'Free trial hopping',
    categoryTags: ['fitness'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 35,
    terms: 'Free first class',
    matchNames: ['free trial hopping'],
  },

  // ── Software ──
  {
    providerId: 'canva-pro',
    name: 'Canva Pro',
    categoryTags: ['software'],
    baseUrl: 'https://www.canva.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 55,
    terms: '$12.99/mo',
    matchNames: ['canva pro'],
  },
  {
    providerId: 'affinity-suite',
    name: 'Affinity Suite',
    categoryTags: ['software'],
    baseUrl: 'https://affinity.serif.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 50,
    terms: 'One-time $169',
    matchNames: ['affinity suite'],
  },
  {
    providerId: 'gimp-inkscape',
    name: 'GIMP + Inkscape',
    categoryTags: ['software'],
    baseUrl: 'https://www.gimp.org',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 60,
    terms: 'Free, open source',
    matchNames: ['gimp + inkscape'],
  },
  {
    providerId: 'google-workspace',
    name: 'Google Workspace',
    categoryTags: ['software'],
    baseUrl: 'https://workspace.google.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 65,
    terms: 'Free personal tier',
    matchNames: ['google workspace'],
  },
  {
    providerId: 'libreoffice',
    name: 'LibreOffice',
    categoryTags: ['software'],
    baseUrl: 'https://www.libreoffice.org',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 60,
    terms: 'Free, open source',
    matchNames: ['libreoffice'],
  },
  {
    providerId: 'google-drive',
    name: 'Google Drive',
    categoryTags: ['cloud_storage', 'software'],
    baseUrl: 'https://drive.google.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 65,
    terms: '15GB free',
    matchNames: ['google drive'],
  },
  {
    providerId: 'icloud',
    name: 'iCloud',
    categoryTags: ['cloud_storage'],
    baseUrl: 'https://www.icloud.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 45,
    terms: '$0.99/mo for 50GB',
    matchNames: ['icloud'],
  },
  {
    providerId: 'bitwarden',
    name: 'Bitwarden',
    categoryTags: ['software'],
    baseUrl: 'https://bitwarden.com',
    affiliateUrl: 'https://bitwarden.com/?ref=leakywallet',
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 75,
    terms: 'Free, open source',
    matchNames: ['bitwarden'],
  },
  {
    providerId: 'apple-keychain',
    name: 'Apple Keychain',
    categoryTags: ['software'],
    baseUrl: 'https://support.apple.com/en-us/HT204085',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 50,
    terms: 'Free for Apple users',
    matchNames: ['apple keychain'],
  },
  {
    providerId: 'apple-google-builtin',
    name: 'Apple/Google built-in',
    categoryTags: ['software'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 50,
    terms: 'Free password manager',
    matchNames: ['apple/google built-in'],
  },

  // ── News & Media ──
  {
    providerId: 'library-card',
    name: 'Library card',
    categoryTags: ['news_media'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 70,
    terms: 'Free access',
    matchNames: ['library card'],
  },
  {
    providerId: 'apple-news-plus',
    name: 'Apple News+',
    categoryTags: ['news_media'],
    baseUrl: 'https://www.apple.com/apple-news',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US', 'CA', 'GB', 'AU'],
    isActive: true,
    priority: 45,
    terms: '$12.99/mo',
    matchNames: ['apple news+', 'apple news plus'],
  },
  {
    providerId: 'library-access',
    name: 'Library access',
    categoryTags: ['news_media'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 65,
    terms: 'Free through libraries',
    matchNames: ['library access'],
  },
  {
    providerId: 'bloomberg-free',
    name: 'Bloomberg free',
    categoryTags: ['news_media'],
    baseUrl: 'https://www.bloomberg.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 50,
    terms: 'Free articles',
    matchNames: ['bloomberg free'],
  },
  {
    providerId: 'edu-email',
    name: '.edu email',
    categoryTags: ['news_media'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['US'],
    isActive: true,
    priority: 55,
    terms: 'Free with student email',
    matchNames: ['.edu email'],
  },
  {
    providerId: 'amazon-prime',
    name: 'Amazon Prime',
    categoryTags: ['news_media', 'streaming'],
    baseUrl: 'https://www.amazon.com/prime',
    affiliateUrl: 'https://www.amazon.com/prime?tag=leakywallet-20',
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 50,
    terms: 'Discounted rate for members',
    matchNames: ['amazon prime'],
  },

  // ── Cloud Storage ──
  {
    providerId: 'google-photos',
    name: 'Google Photos',
    categoryTags: ['cloud_storage'],
    baseUrl: 'https://photos.google.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 60,
    terms: 'Free backup',
    matchNames: ['google photos'],
  },
  {
    providerId: 'external-hdd',
    name: 'External hard drive',
    categoryTags: ['cloud_storage'],
    baseUrl: 'https://www.amazon.com/s?k=external+hard+drive',
    affiliateUrl: 'https://www.amazon.com/s?k=external+hard+drive&tag=leakywallet-20',
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 40,
    terms: 'One-time ~$50',
    matchNames: ['external hard drive'],
  },
  {
    providerId: 'cleanup-gmail',
    name: 'Clean up Gmail',
    categoryTags: ['cloud_storage'],
    baseUrl: '',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 55,
    terms: 'Free up space',
    matchNames: ['clean up gmail'],
  },
  {
    providerId: 'icloud-50gb',
    name: 'iCloud 50GB',
    categoryTags: ['cloud_storage'],
    baseUrl: 'https://www.icloud.com',
    affiliateUrl: null,
    network: 'generic',
    countryAvailability: ['*'],
    isActive: true,
    priority: 45,
    terms: '$0.99/mo',
    matchNames: ['icloud 50gb'],
  },
]

// ── Indexes ────────────────────────────────────────────────────────

const providerById = new Map<string, AffiliateProvider>()
const providerByName = new Map<string, AffiliateProvider>()

for (const p of PROVIDERS) {
  providerById.set(p.providerId, p)
  for (const name of p.matchNames) {
    providerByName.set(name.toLowerCase(), p)
  }
}

// ── Exports ────────────────────────────────────────────────────────

export function getProvider(id: string): AffiliateProvider | null {
  return providerById.get(id) ?? null
}

export function findProviderByName(name: string): AffiliateProvider | null {
  return providerByName.get(name.trim().toLowerCase()) ?? null
}

export function getProviderLink(id: string): string | null {
  const provider = providerById.get(id)
  if (!provider || !provider.isActive) return null
  if (provider.affiliateUrl && isAffiliateEnabled()) {
    return `/api/redirect?pid=${encodeURIComponent(id)}`
  }
  return provider.baseUrl || null
}

export function isAffiliateEnabled(): boolean {
  if (typeof process === 'undefined') return true
  const flag = process.env.NEXT_PUBLIC_AFFILIATE_ENABLED
  return flag !== 'false'
}

export function getRegistryConfig(): RegistryConfig {
  return {
    disclosureText: 'We may earn a commission at no extra cost to you.',
    footerNote: 'Alternatives are generated algorithmically based on category and pricing.',
  }
}

export function getAllProviders(): AffiliateProvider[] {
  return PROVIDERS.filter(p => p.isActive)
}
