/**
 * Hardcoded demo results for instant "Try Demo" mode.
 * No API call needed — renders immediately with a short progress animation.
 */

export const DEMO_RESULTS = {
  monthly_leak: 487.42,
  annual_savings: 5849.04,
  top_leaks: [
    {
      category: 'Subscription',
      merchant: 'NETFLIX',
      monthly_cost: 22.99,
      yearly_cost: 275.88,
      explanation: 'Recurring monthly charge detected across 12 months',
    },
    {
      category: 'Subscription',
      merchant: 'SPOTIFY PREMIUM',
      monthly_cost: 11.99,
      yearly_cost: 143.88,
      explanation: 'Recurring monthly music subscription',
    },
    {
      category: 'Subscription',
      merchant: 'ADOBE CREATIVE CLOUD',
      monthly_cost: 54.99,
      yearly_cost: 659.88,
      explanation: 'Recurring monthly software subscription',
    },
    {
      category: 'Subscription',
      merchant: 'HELLO FRESH MEAL KIT',
      monthly_cost: 59.99,
      yearly_cost: 719.88,
      explanation: 'Recurring meal kit delivery every month',
    },
    {
      category: 'Food Delivery',
      merchant: 'UBER EATS',
      monthly_cost: 131.35,
      yearly_cost: 1576.20,
      explanation: 'Food delivery: 48 orders totaling $1,576.20',
    },
    {
      category: 'Fees & Charges',
      merchant: 'MONTHLY ACCOUNT FEE',
      monthly_cost: 10.00,
      yearly_cost: 120.00,
      explanation: 'Bank fees: 12 charges totaling $120.00',
    },
    {
      category: 'Fees & Charges',
      merchant: 'ATM WITHDRAWAL FEE',
      monthly_cost: 2.50,
      yearly_cost: 30.00,
      explanation: 'ATM fees: 12 charges totaling $30.00',
    },
    {
      category: 'Subscription',
      merchant: 'HEADSPACE APP',
      monthly_cost: 14.99,
      yearly_cost: 179.88,
      explanation: 'Recurring monthly wellness app subscription',
    },
    {
      category: 'Subscription',
      merchant: 'ANYTIME FITNESS',
      monthly_cost: 49.99,
      yearly_cost: 599.88,
      explanation: 'Monthly gym membership detected',
    },
    {
      category: 'Subscription',
      merchant: 'MICROSOFT 365',
      monthly_cost: 12.99,
      yearly_cost: 155.88,
      explanation: 'Recurring monthly software subscription',
    },
  ],
  top_spending: [
    { date: '2024-04-03', merchant: 'AIRBNB BOOKING', amount: 620.00, category: 'Travel' },
    { date: '2024-04-02', merchant: 'QANTAS AIRWAYS', amount: 485.00, category: 'Travel' },
    { date: '2024-11-15', merchant: 'APPLE STORE', amount: 399.00, category: 'Shopping' },
    { date: '2024-09-11', merchant: 'BOOKING.COM HOTEL', amount: 340.00, category: 'Travel' },
    { date: '2024-09-10', merchant: 'JETSTAR FLIGHT', amount: 289.00, category: 'Travel' },
  ],
  easy_wins: [
    {
      title: 'Consolidate streaming services',
      estimated_yearly_savings: 275.88,
      action: 'Keep only 1-2 streaming services you actually watch. Rotate subscriptions monthly instead of paying for all.',
    },
    {
      title: 'Reduce delivery orders',
      estimated_yearly_savings: 788.10,
      action: 'Set a weekly delivery budget. Try meal prepping on Sundays to reduce takeout frequency.',
    },
    {
      title: 'Switch to fee-free banking',
      estimated_yearly_savings: 150.00,
      action: 'Open account with an online bank or credit union to eliminate ATM and account fees.',
    },
    {
      title: 'Audit Adobe Creative Cloud usage',
      estimated_yearly_savings: 659.88,
      action: 'Consider Canva Pro ($12.99/mo) or free alternatives like GIMP + Inkscape if you don\'t use the full suite.',
    },
    {
      title: 'Audit gym membership usage',
      estimated_yearly_savings: 599.88,
      action: 'Track gym visits for 2 weeks - if less than 8 visits per month, cancel and use free alternatives.',
    },
  ],
  recovery_plan: [
    'Week 1: Audit all 8 subscriptions - cancel or pause unused ones',
    'Week 2: Set weekly food delivery budget of $30',
    'Week 3: Research and open a fee-free bank account',
    'Month 2: Track all discretionary spending for 30 days',
    'Set up automatic transfers of saved money to separate savings account',
    'Schedule monthly 15-minute spending reviews to maintain awareness',
    'Goal: Reduce monthly leaks from $487 to $244',
  ],
  category_summary: [
    {
      category: 'Groceries',
      total: 7124.52,
      percent: 28.4,
      transaction_count: 96,
      top_merchants: [
        { name: 'WOOLWORTHS', total: 3280.40 },
        { name: 'COLES', total: 2510.12 },
        { name: 'ALDI', total: 586.80 },
      ],
    },
    {
      category: 'Dining & Delivery',
      total: 4812.60,
      percent: 19.2,
      transaction_count: 132,
      top_merchants: [
        { name: 'UBER EATS', total: 1576.20 },
        { name: 'STARBUCKS', total: 1025.40 },
        { name: 'DOORDASH', total: 540.00 },
      ],
    },
    {
      category: 'Subscriptions',
      total: 2741.04,
      percent: 10.9,
      transaction_count: 96,
      top_merchants: [
        { name: 'HELLO FRESH', total: 719.88 },
        { name: 'ADOBE', total: 659.88 },
        { name: 'ANYTIME FITNESS', total: 599.88 },
      ],
    },
    {
      category: 'Utilities & Bills',
      total: 3959.88,
      percent: 15.8,
      transaction_count: 48,
      top_merchants: [
        { name: 'AGL ELECTRICITY', total: 1905.00 },
        { name: 'TELSTRA INTERNET', total: 959.88 },
        { name: 'OPTUS MOBILE', total: 660.00 },
      ],
    },
    {
      category: 'Transport',
      total: 2266.80,
      percent: 9.0,
      transaction_count: 84,
      top_merchants: [
        { name: 'SHELL PETROL', total: 856.80 },
        { name: 'UBER TRIP', total: 974.40 },
        { name: 'OPAL CARD', total: 600.00 },
      ],
    },
    {
      category: 'Shopping',
      total: 2489.40,
      percent: 9.9,
      transaction_count: 36,
      top_merchants: [
        { name: 'AMAZON', total: 1109.40 },
        { name: 'APPLE STORE', total: 798.00 },
        { name: 'IKEA', total: 756.00 },
      ],
    },
    {
      category: 'Entertainment',
      total: 719.88,
      percent: 2.9,
      transaction_count: 24,
      top_merchants: [
        { name: 'STEAM', total: 359.88 },
        { name: 'EVENT CINEMAS', total: 168.00 },
        { name: 'TICKETMASTER', total: 380.00 },
      ],
    },
    {
      category: 'Fees',
      total: 390.00,
      percent: 1.6,
      transaction_count: 34,
      top_merchants: [
        { name: 'MONTHLY ACCOUNT FEE', total: 120.00 },
        { name: 'ATM WITHDRAWAL FEE', total: 30.00 },
        { name: 'OVERDRAFT FEE', total: 60.00 },
      ],
    },
    {
      category: 'Health & Fitness',
      total: 559.00,
      percent: 2.2,
      transaction_count: 16,
      top_merchants: [
        { name: 'BUPA HEALTH INSURANCE', total: 559.50 },
        { name: 'PRICELINE PHARMACY', total: 195.00 },
        { name: 'DR SMITH MEDICAL', total: 340.00 },
      ],
    },
  ],
  subscriptions: [
    { merchant: 'HELLO FRESH MEAL KIT', monthly_cost: 59.99, annual_cost: 719.88, confidence: 0.95, last_date: '2024-12-12', occurrences: 12, reason: 'Same amount every month for 12 months' },
    { merchant: 'ADOBE CREATIVE CLOUD', monthly_cost: 54.99, annual_cost: 659.88, confidence: 0.95, last_date: '2024-12-07', occurrences: 12, reason: 'Same amount every month for 12 months' },
    { merchant: 'ANYTIME FITNESS', monthly_cost: 49.99, annual_cost: 599.88, confidence: 0.95, last_date: '2024-12-05', occurrences: 12, reason: 'Same amount every month for 12 months' },
    { merchant: 'NETFLIX', monthly_cost: 22.99, annual_cost: 275.88, confidence: 0.9, last_date: '2024-12-03', occurrences: 12, reason: 'Monthly recurring - price increased from $15.99 to $22.99 in July' },
    { merchant: 'HEADSPACE APP', monthly_cost: 14.99, annual_cost: 179.88, confidence: 0.95, last_date: '2024-12-18', occurrences: 12, reason: 'Same amount every month for 12 months' },
    { merchant: 'MICROSOFT 365', monthly_cost: 12.99, annual_cost: 155.88, confidence: 0.95, last_date: '2024-12-15', occurrences: 12, reason: 'Same amount every month for 12 months' },
    { merchant: 'SPOTIFY PREMIUM', monthly_cost: 11.99, annual_cost: 143.88, confidence: 0.95, last_date: '2024-12-03', occurrences: 12, reason: 'Same amount every month for 12 months' },
    { merchant: 'ICLOUD STORAGE', monthly_cost: 3.99, annual_cost: 47.88, confidence: 0.95, last_date: '2024-12-10', occurrences: 12, reason: 'Same amount every month for 12 months' },
  ],
  comparison: {
    previous_month: '2024-11',
    current_month: '2024-12',
    previous_total: 2845.20,
    current_total: 2620.40,
    total_change: -224.80,
    total_change_percent: -7.9,
    top_changes: [
      { category: 'Shopping', previous: 689.95, current: 423.94, change: -266.01, change_percent: -38.6 },
      { category: 'Dining & Delivery', previous: 385.60, current: 342.10, change: -43.50, change_percent: -11.3 },
      { category: 'Transport', previous: 198.20, current: 208.60, change: 10.40, change_percent: 5.2 },
      { category: 'Subscriptions', previous: 232.92, current: 232.92, change: 0, change_percent: 0 },
      { category: 'Utilities & Bills', previous: 279.99, current: 279.99, change: 0, change_percent: 0 },
    ],
    spikes: [],
    months_analyzed: 12,
  },
  alternatives: [
    { original: 'Adobe Creative Cloud', alternative: 'GIMP + Inkscape', current_price: 54.99, alternative_price: 0, monthly_savings: 54.99, yearly_savings: 659.88, note: 'Free open source alternatives', category: 'software' },
    { original: 'Adobe Creative Cloud', alternative: 'Canva Pro', current_price: 54.99, alternative_price: 12.99, monthly_savings: 42.00, yearly_savings: 504.00, note: 'Good for most design needs', category: 'software' },
    { original: 'Uber Eats', alternative: 'Restaurant pickup', current_price: 131.35, alternative_price: 0, monthly_savings: 131.35, yearly_savings: 1576.20, note: 'Save 20-30% on fees', category: 'food_delivery' },
    { original: 'Spotify', alternative: 'Spotify Free', current_price: 11.99, alternative_price: 0, monthly_savings: 11.99, yearly_savings: 143.88, note: 'Free tier with ads', category: 'streaming' },
    { original: 'Netflix', alternative: 'Tubi', current_price: 22.99, alternative_price: 0, monthly_savings: 22.99, yearly_savings: 275.88, note: 'Free with ads, good movie selection', category: 'streaming' },
    { original: 'Microsoft 365', alternative: 'Google Workspace', current_price: 12.99, alternative_price: 0, monthly_savings: 12.99, yearly_savings: 155.88, note: 'Free personal tier', category: 'software' },
  ],
  price_changes: [
    {
      merchant: 'NETFLIX',
      old_price: 15.99,
      new_price: 22.99,
      increase: 7.00,
      percent_change: 43.8,
      first_date: '2024-01-03',
      latest_date: '2024-12-03',
      yearly_impact: 84.00,
    },
  ],
  duplicate_subscriptions: [
    {
      category: 'Streaming & Music',
      services: ['NETFLIX', 'SPOTIFY PREMIUM'],
      count: 2,
      combined_monthly: 34.98,
      combined_yearly: 419.76,
      suggestion: 'Consider if you need both a video and music streaming service simultaneously.',
    },
  ],
  share_summary: {
    monthly_leak: 487.42,
    annual_savings: 5849.04,
    top_categories: [
      { category: 'Food Delivery', monthly: 131.35 },
      { category: 'Subscription', monthly: 232.92 },
      { category: 'Fees & Charges', monthly: 12.50 },
    ],
    subscription_count: 8,
    tagline: 'I found $5,849/year in hidden spending leaks!',
  },
  disclaimer: 'This analysis is for informational purposes only. Not financial advice.',
}
